apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-api-secrets
  labels:
    {{- include "your-chart-name.labels" . | nindent 4 }}
type: Opaque
data:
  OPENAI_API_KEY: {{ .Values.config.openai.apiKey | b64enc | quote }}
  OPENAI_MODEL: {{ .Values.config.openai.model | b64enc | quote }}
  SQL_DB_PATH: {{ .Values.config.sql.dbPath | b64enc | quote }}
  NEO4J_URI: {{ .Values.config.neo4j.uri | b64enc | quote }}
  NEO4J_USERNAME: {{ .Values.config.neo4j.username | b64enc | quote }}
  NEO4J_PASSWORD: {{ .Values.config.neo4j.password | b64enc | quote }}
  NEO4J_ACCEPT_LICENSE_AGREEMENT: {{ .Values.config.neo4j.acceptLicense | b64enc | quote }}
  SMTP_SERVER: {{ .Values.config.smtp.server | b64enc | quote }}
  SMTP_PORT: {{ .Values.config.smtp.port | toString | b64enc | quote }}
  EMAIL_USER: {{ .Values.config.smtp.emailUser | b64enc | quote }}
  EMAIL_PASSWORD: {{ .Values.config.smtp.emailPassword | b64enc | quote }}
  DEFAULT_RECIPIENT: {{ .Values.config.smtp.defaultRecipient | b64enc | quote }}
  AZURE_DOC_ENDPOINT: {{ .Values.config.azure.docEndpoint | b64enc | quote }}
  AZURE_DOC_KEY: {{ .Values.config.azure.docKey | b64enc | quote }}
  AZURE_OCR_URL: {{ .Values.config.azure.ocrUrl | b64enc | quote }} 