# Default values for hello-world.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
# Default configuration values
config:
  openai:
    apiKey: ""  # Fill in deployment
    model: "gpt-4o-mini"
  sql:
    dbPath: ""  # Fill in deployment
  neo4j:
    uri: "bolt://localhost:7687"
    username: ""  # Fill in deployment
    password: ""  # Fill in deployment
    acceptLicense: "yes"
  smtp:
    server: "smtp.gmail.com"
    port: 587
    emailUser: "litewaveaidev@gmail.com"
    emailPassword: ""  # Fill in deployment
    defaultRecipient: ""  # Fill in deployment
  azure:
    ocrUrl: ""  # Fill in deployment
    docEndpoint: ""  # Fill in deployment
    docKey: ""  # Fill in deployment

# Deployment configuration
image:
  repository: litewavedev/docaiapp
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  # tag: "latest"

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

service:
  type: NodePort
  port: 80