name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build
      run: make build
      env:
        DOCKER_REGISTRY_USER: ${{ env.DOCKER_REGISTRY_USER }}
        DOCKER_REGISTRY_PASS: ${{ secrets.DOCKER_REGISTRY_PASS }}

    - name: push
      run: make push
      env:
        DOCKER_REGISTRY_USER: ${{ env.DOCKER_REGISTRY_USER }}
        DOCKER_REGISTRY_PASS: ${{ secrets.DOCKER_REGISTRY_PASS }}

    - name: Release
      run: make release
      env:
        DOCKER_REGISTRY_USER: ${{ env.DOCKER_REGISTRY_USER }}
        DOCKER_REGISTRY_PASS: ${{ secrets.DOCKER_REGISTRY_PASS }}
