name: Build CI

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - 'helm/**'
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - 'helm/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: login
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKER_REGISTRY_USER }}
        password: ${{ secrets.DOCKER_REGISTRY_PASS }}
        
    - name: Build
      run: make build
      env:
        DOCKER_REGISTRY_USER: ${{ vars.DOCKER_REGISTRY_USER }}