name: Release Helm Chart

on:
  release:
    types: [published]

jobs:
  release-helm-chart:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_TOKEN }}
          ref: main

      - name: Get release version
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Update Chart.yaml version
        run: |
          sed -i "s/^version:.*$/version: ${{ steps.get_version.outputs.VERSION }}/" ./helm/Chart.yaml
          sed -i "s/^appVersion:.*$/appVersion: ${{ steps.get_version.outputs.VERSION }}/" ./helm/Chart.yaml

      - name: Commit and push changes
        run: |
          git config --global user.name 'tejasrajeevab'
          git config --global user.email 'tejasrajeevab@gmail.com'
          git add ./helm/Chart.yaml
          git commit -m "CI UPDATE VIA PAT: update helm chart version to ${{ steps.get_version.outputs.VERSION }}"
          git push 