name: Release CI

on:
  release:
    types: [published]

jobs:
  release-image:
      runs-on: ubuntu-latest

      steps:
      - uses: actions/checkout@v4

      - name: login
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_REGISTRY_USER }}
          password: ${{ secrets.DOCKER_REGISTRY_PASS }}
          
      - name: Build
        run: make build
        env:
          DOCKER_REGISTRY_USER: ${{ vars.DOCKER_REGISTRY_USER }}

      - name: push
        run: make push
        env:
          DOCKER_REGISTRY_USER: ${{ vars.DOCKER_REGISTRY_USER }}
          RELEASE: ${{ github.event.release.tag_name }}

      - name: Release
        run: make release
        env:
          DOCKER_REGISTRY_USER: ${{ vars.DOCKER_REGISTRY_USER }}
          RELEASE: ${{ github.event.release.tag_name }}

  release-helm-chart:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Get release version
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Update Chart.yaml version
        run: |
          sed -i "s/^version:.*$/version: ${{ steps.get_version.outputs.VERSION }}/" ./helm/Chart.yaml
          sed -i "s/^appVersion:.*$/appVersion: ${{ steps.get_version.outputs.VERSION }}/" ./helm/Chart.yaml

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add ./helm/Chart.yaml
          git commit -m "chore: update helm chart version to ${{ steps.get_version.outputs.VERSION }}"
          git push 